---
- hosts: webserver
  become: yes
  #vars:
  #  tomcat_ip: 10.10.2.220
  #  jenkins_ip: 10.10.2.39

  tasks:
  - name: "upgrading package"
    yum:
      name: '*'
      state: latest
 # - name: "install tomcat8"
 #   apt: 
 #     name: tomcat8
 #     action: install
 # - name: "starting tomcat service"
 #   service:
 #     name: tomcat8
 #     action: start

  # deployig gameoflife war in tomcat
  - name: "copying war file into webapps"
    get_url:
      url: http://ftp-nyc.osuosl.org/pub/jenkins/war-stable/2.107.3/jenkins.war
      dest: /opt/tomcat/webapps/
      mode: 755
    notify: Restart tomcat    
- handlers:
  - name: Restart tomcat
    service:
      name: tomcat
      state: restarted
