---
- hosts: webserver
  become: yes
  vars:
    tomcat_ip: 10.10.2.220
    jenkins_ip: 10.10.2.39

  tasks:
  - name: "updating package"
    apt:
      update_cache: yes
 # - name: "install tomcat8"
 #   apt: 
 #     name: tomcat8
 #     action: install
 # - name: "starting tomcat service"
 #   service:
 #     name: tomcat8
 #     action: start

  # deployig gameoflife war in tomcat
  - name: "copying war file into webapps"
    copy:
    src: {{jenkins_ip}}:/var/lib/jenkins/workspace/gameoflife-tomcat/gameoflife-web/target/gameoflife.war
    dest: {{tomcat_ip}}:/opt/tomcat/webapps/
    remote_src: yes      
    notify: Restart tomcat8    
- handlers:
  - name: Restart tomcat8
    service:
      name: tomcat8
      state: restarted