---
- hosts: 10.10.2.220
  become: yes
  #vars:
  #  tomcat_ip: 10.10.2.220
  #  jenkins_ip: 10.10.2.39

  tasks:
  - name: "upgrading package"
    yum:
      name: '*'
      state: latest
 # - name: "install tomcat8"
 #   apt: 
 #     name: tomcat8
 #     action: install
 # - name: "starting tomcat service"
 #   service:
 #     name: tomcat8
 #     action: start

  # deployig gameoflife war in tomcat
  - name: "copying war file into webapps"
    get_url:
      url: http://18.188.19.117:8080/job/gameoflife123/ws/gameoflife-web/target/gameoflife.war
      dest: /opt/tomcat/webapps/gameoflife.war
      mode: 755
  #  copy:
  #  src: 10.10.2.220:/var/lib/jenkins/workspace/gameoflife-tomcat/gameoflife-web/target/gameoflife.war
  #  dest: 10.10.2.39:/opt/tomcat/webapps/
  #  remote_src: yes      
    notify: Restart tomcat8    
- handlers:
  - name: Restart tomcat8
    service:
      name: tomcat8
      state: restarted
